# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['authenticate_if_needed']

# %% ../nbs/00_core.ipynb 5
def authenticate_if_needed():
    """Authenticate Earth Engine, if credentials do not exist.

    * Authenticate, if needed."""

    import ee
    import os

    if os.path.exists(ee.oauth.get_credentials_path()):
        print('\N{check mark} Authentication credentials were found.')
    else:
        ee.Authenticate()
