# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_panel.ipynb.

# %% auto 0
__all__ = ['MapInspectorHBox']

# %% ../nbs/02_panel.ipynb 4
from .ipyleaflet import Map
from .ipyleaflet import Inspector
import ipywidgets
from traitlets import Unicode

# %% ../nbs/02_panel.ipynb 6
class MapInspectorHBox(ipywidgets.HBox):
    """A panel that includes a map and Inspector widget."""
    
    def __init__(self,
                 map_obj=None,
                 **kwargs):
        if map_obj is None:
            kwargs['height'] = '300px'
            map_obj = Map(**kwargs)
        inspector_obj = Inspector(map_obj)
        self.map = map_obj
        self.inspector = inspector_obj

        if 'children' not in kwargs:
            kwargs['children'] = []
        kwargs['children'].insert(0, self.map)
        kwargs['children'].insert(1, self.inspector)
        super().__init__(**kwargs)
