# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/earthengine-jupyter',
                'doc_host': 'https://googlestaging.github.io',
                'git_url': 'https://github.com/googlestaging/earthengine-jupyter',
                'lib_path': 'earthengine_jupyter'},
  'syms': {'earthengine_jupyter.core': {'earthengine_jupyter.core.foo': ('core.html#foo', 'earthengine_jupyter/core.py')}}}